### ISSUE TITLE
Why no 3.0 ;-)

### ISSUE THREAD

**Issue by harikt** [jeremykendall/slim-auth#20]
Hey @jeremykendall ,

Have you got any plans for 3.0 ?

I would like to investigate on my free time. Let me know if I can help you with :-) .

Thank you.

**Comment by jeremykendall** [comment]
I do, but I just haven't had the time, and I have no idea when I'll get the time :disappointed: 

#19 is probably the biggest blocker (besides free time, of course). If you've got any expertise in that area, a helping hand would be much appreciated.

**Comment by harikt** [comment]
Hey @jeremykendall , 

I had a look. Not sure on it. Will look once again in coming days. ( I have not worked on Slim or this library before ) . So you know my experience on the version differences mentioned with 0.7 alpha and 0.6 is not good.

But I will see if I can find something.

Thank you.

**Comment by jeremykendall** [comment]
Thanks!

**Comment by jeremykendall** [comment]
Getting there! https://github.com/jeremykendall/slim-auth/tree/slim-3.x

Once I update the readme I can release the alpha version.

**Comment by harikt** [comment]
@jeremykendall sorry that I wasn't able to make my hands dirty. And thank you for the great work. I will look into when I get sometime. 

By the way I should say, probably name it as psr-7 auth , so it could be used with slim + expressive etc.

Thank you.

**Comment by jeremykendall** [comment]
@harikt No worries! I know how it goes.

> By the way I should say, probably name it as psr-7 auth , so it could be used with slim + expressive etc.

I've considered doing that (great minds!), but I'm going to tackle the Slim v3 upgrade first.

**Comment by harikt** [comment]
> I've considered doing that (great minds!),
> 
> think alike ;) .
> 
> but I'm going to tackle the Slim v3 upgrade first.
> 
> Sure.

Thank you
