### ISSUE TITLE
Can Not Install via Composer

### ISSUE THREAD

**Issue by HughxDev** [jeremykendall/slim-auth#25]
This is via the XAMPP shell (which provides php-cli, etc.) on Windows 7.

Firstly, I had to install composer manually, as `curl` is unavailable on Win.

`# php F:\installer.php`

> All settings correct for using Composer
> Downloading...
> 
> Composer successfully installed to: F:\path\composer.phar
> Use it: php composer.phar

`# composer require jeremykendall/slim-auth`

> 'composer' is not recognized as an internal or external command, operable program or batch file.

`# php composer.phar require jeremykendall/slim-auth`

> [InvalidArgumentException]
> Could not find package jeremykendall/slim-auth at any version for your minimum-stability (stable).
> Check the package spelling or your minimum-stability

**Comment by HughxDev** [comment]
My mistake. Solution: http://stackoverflow.com/a/23741001/214325

**Comment by jeremykendall** [comment]
Awesome! Sorry I didn't get back to you. Work has been crazy.
