### ISSUE TITLE
Vendor name conflict

### ISSUE THREAD

**Issue by solidevolution** [jeremykendall/slim-auth#26]
Hello,

since we use Slim Auth, we got the following error while composer install/update:

Skipped installation of bin bin/version-check for package jeremykendall/slim-auth: name conflicts with an existing file

Any idea?

**Comment by jeremykendall** [comment]
I think that should `bin/version-check` should probably be removed, I just haven't done it yet. That conflict will have no effect on the functionality. You can either
- Ignore the conflict and use Slim Auth as normal
- Take the extra step of removing it and submit a PR :-)

Thanks for reminding me that should go, and thanks for using Slim Auth! It's an honor to see this project in use in the wild.

**Comment by do3meli** [comment]
Will you backport this and other changes to the slim-2.x branch?

**Comment by jeremykendall** [comment]
@do3meli Absolutely. I goofed up the commits I made last night when I was putting all of this together. I thought I'd successfully backported all the changes, but obviously I didn't :frowning:. Oops!

**Comment by jeremykendall** [comment]
@do3meli It looks like my goof was the other way around. All of the changes made it into the 2.x branch but no the 3.x branch. See the Oct 5 commits: https://github.com/jeremykendall/slim-auth/commits/slim-2.x

Am I missing something?

**Comment by do3meli** [comment]
hmm @jeremykendall i think you still miss some commits yes. for example i am still seeing version_check in the bin directory when browsing the 2.x branch: https://github.com/jeremykendall/slim-auth/tree/slim-2.x/bin - mainly the commits you have done to the develop branch AFTER you merged my changes is missing in slim 2.x branch. (not all of them are really needed - all the 3.x specifics can stay where they are)

**Comment by jeremykendall** [comment]
Good catch! Just pushed the commit that remove `/bin` from the `slim-2.x` branch. Can you see any others I missed?

**Comment by jeremykendall** [comment]
@do3meli I think I got them all. Let me know if I missed anything else. Thanks!

**Comment by do3meli** [comment]
hey @jeremykendall, thanks for the merge. i think you could even push these commits to the 2.x branch to keep it as close as possible to the develop branch:

https://github.com/jeremykendall/slim-auth/commit/72bb153156fbd7df747f98f6b68824746e66f7da
https://github.com/jeremykendall/slim-auth/commit/ef66012ff3918b51e93dea7eea17a0f297a9f0e3
https://github.com/jeremykendall/slim-auth/commit/9e8f52010ee618e667d3449fddbc2a22e647db73

but functionality wise i think you have covered everything now ;-)

thanks for your effort.
cheers dom

**Comment by jeremykendall** [comment]
Done! Thanks!
