### ISSUE TITLE
Update documentation to point out deprecated salt (as of PHP 7).

### ISSUE THREAD

**Issue by jeremykendall** [jeremykendall/slim-auth#34]
Report via this tweet: https://twitter.com/devbrilliance/status/683447669709271040.

**Comment by jeremykendall** [comment]
Also update the blog post.

**Comment by wkhayrattee** [comment]
thanks for all you do @jeremykendall 
You are a superhero!!!

**Comment by jeremykendall** [comment]
@7php Thanks! You're too kind :bow:

**Comment by jeremykendall** [comment]
Oops! This should have been opened against https://github.com/jeremykendall/password-validator. Closing this and moving it to the correct repo.
