### ISSUE TITLE
determineRouteBeforeAppMiddleware

### ISSUE THREAD

**Issue by urshofer** [jeremykendall/slim-auth#37]
I'd like just to note that for slim 3.x, the parameter `determineRouteBeforeAppMiddleware`need to be set to `true`during startup, otherwise the auth middleware cannot determine the current route. It should be stated in the docs.

Thanks for your great work!
Urs

**Comment by jeremykendall** [comment]
Excellent point! Thanks!

**Comment by pip8786** [comment]
For anyone else checking this, this is how you initialize it:
`$container = new \Slim\Container(['settings'=>['determineRouteBeforeAppMiddleware'=>true]]);`

**Comment by jeremykendall** [comment]
Fixed in e5383b7, merged into the 3.x branch and released in [2.0.0-alpha+005](https://github.com/jeremykendall/slim-auth/releases/tag/2.0.0-alpha%2B005).

Thanks for opening the issue. Sorry I didn't document this requirement at all :-(
