### ISSUE TITLE
Documentation / example code

### ISSUE THREAD

**Issue by jernejsk** [jeremykendall/slim-auth#40]
Hi, I wanted to try out this code but I'm bit stuck. In your readme there is an example code which uses Bootstrap class which is not present anymore. Can you please update your example code?

**Comment by jeremykendall** [comment]
@jernejsk What version of Slim Auth are you using? I'm guessing it's one of the v2 alpha releases for Slim 3.x compatibility. If that's the case, the most recent docs are in the Slim 3.x branch here: https://github.com/jeremykendall/slim-auth/tree/slim-3.x.

**Comment by jernejsk** [comment]
Yes, you are correct. I totaly miss them. Thanks.

**Comment by jeremykendall** [comment]
No problem! Thanks for giving Slim Auth a try!
