### ISSUE TITLE
Authentication failing(3.x)

### ISSUE THREAD

**Issue by MLGeorge88** [jeremykendall/slim-auth#41]
Hi Jeremy,
I have implemented the build for Slim 3.x, but I am having an issue with the authentication. When I send a username and password, it returns as a failed login attempt. I am not sure why. It is checking the correct table and columns for identity and credentials. Password is currently hashed as MD5. A role is set(admin). 

No errors are being thrown by PHP. How can I go about figuring out what could be causing it to fail? Happy to share any code that would help.

**Comment by jeremykendall** [comment]
Hey there! Happy to help.

If your current scheme is MD5 hashing, how are you configuring that for Slim Auth? Can you share how you've integrated the lib without sharing any confidential info?

**Comment by MLGeorge88** [comment]
Thanks for the reply! I have nothing confidential at all, so I'll just paste the relevant chunks of code below. I am not 100% sure what you mean by configuring that for Slim Auth. I haven't done anything specific for it, so that may be my issue. 

My Login route:

``` php
$app->map(['GET', 'POST'], '/login', function ($request, $response, $args) {
    $params = $request->getParsedBody();

    if ($request->isPost()) {
        $username = $params['username'];
        $password = $params['password'];

        $result = $this->get('authenticator')->authenticate($username, $password);

        if ($result->isValid()) {
          //Success login attempt
          $app->redirect('/cities');
        }
        //Failed Login Attempt
        die("Failed");
    }
    $this->renderer->render($response, 'login.phtml', $args);
    return $response;
});
```

My Dependencies:

``` php
// Authenticator
$container['authAdapter'] = function ($c) {
    $db = $c['db'];
    $adapter = new \JeremyKendall\Slim\Auth\Adapter\Db\PdoAdapter(
        $db,
        'users',
        'username',
        'password',
        new \JeremyKendall\Password\PasswordValidator()
    );

    return $adapter;
};

// Authorization
$container['acl'] = function ($c) {
    return new Acl();
};

$container->register(
  new \JeremyKendall\Slim\Auth\ServiceProvider\SlimAuthProvider()
);
```

My Middleware:

``` php
$app->add($app->getContainer()->get('slimAuthRedirectMiddleware'));
```

**Comment by MLGeorge88** [comment]
So trying to jump ahead so as to not make you do all the work...

Everything is working correctly if I hash a new password using the PASSWORD_DEFAULT(bcrypt). So its definitely how I'm(not) configuring Slim Auth for MD5. I saw there is a method to rehash passwords if they aren't using the correct hash type. So I'm guessing what I need to do is configure it to use MD5 then use the rehash to change the hash type after a successful login?

**Comment by jeremykendall** [comment]
Exactly!

Not at my keyboard right this second, so I can't give you specific direction, but it has to do with the UpgradeDecorator in the Password Validator dependency. (Working from memory here. I'll be able to help more when/if I get my toddler down for his nap. :P )

**Comment by MLGeorge88** [comment]
Would definitely appreciate that! I'd be happy to swap with him, he can stay up and write code and I'll take a nap :)

**Comment by jeremykendall** [comment]
LOL. Let's all just take naps :-)

The password validation algorithm is found in the 4th arg to the auth adapter (see this example): https://github.com/jeremykendall/slim-auth/blob/slim-3.x/README.md#sample-container-service-configuration

**Comment by jeremykendall** [comment]
I'd submit that if this is a new project, you should use bcrypt hashes, no questions asked. If not, you should upgrade to bcrypt. Both are possible using Slim Auth.

**Comment by jeremykendall** [comment]
Here's an example of how to decorate the PasswordValidator in order to use a legacy validation algorithm https://github.com/jeremykendall/password-validator/blob/develop/README.md#upgrading-legacy-passwords

**Comment by jeremykendall** [comment]
The point is to upgrade to no longer use insecure password hashes though, so if this is a new project you should definitely use bcrypt and not md5 or anything else.

**Comment by MLGeorge88** [comment]
Its a complete re-write of an existing project. So unfortunately I'll have existing user data, so I'll have to use the rehash, which is what I had planned. Currently we're actually using SHA512, I just used MD5 for my quick demo/test. 

Thanks for those links, that should get me the rest of the way there! Appreciate the help, I'll post up if I run into any issues using the rehash.

**Comment by jeremykendall** [comment]
> Its a complete re-write of an existing project. So unfortunately I'll have existing user data, so I'll have to use the rehash, which is what I had planned.

That's awesome! Upgrading existing hashes is one of the primary use cases for password validator. I'm happy to see it in action!

> I just used MD5 for my quick demo/test.

Makes perfect sense.

> Appreciate the help, I'll post up if I run into any issues using the rehash.

You got it! Please feel free to hit me up with any other questions you have. Happy to help however I can.

**Comment by jeremykendall** [comment]
I'm going to close this for now. Please feel free to reopen it if you have any more questions!
