### ISSUE TITLE
hasIdentity and hooks in slim3

### ISSUE THREAD

**Issue by Bigua** [jeremykendall/slim-auth#43]
Hi

Since Slim 3 has no more Hooks, how can I test hasIdentity in a twig view on slim 3? Seems to me that I need to translate the $app->hook (...) into a Middleware, any Ideas?

**Comment by jeremykendall** [comment]
If you're going to use Slim Auth with Slim 3, make sure to check out the slim-3.x branch for the latest docs and middlewares: https://github.com/jeremykendall/slim-auth/tree/slim-3.x. Sorry for the confusion!

**Comment by Bigua** [comment]
Hi Jeremy, first: tnx a lot by this module!
 I was using the wrong branch,sorry

**Comment by jeremykendall** [comment]
No problem! Totally my fault due to the repo being in a confusing state.

Thanks for trying out the library! If there's anything else I can do to help, please let me know.
